# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ultra_enclosure_manager.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QGroupBox,
    QLabel, QPushButton, QSizePolicy, QSpinBox,
    QWidget)
import usm_rc

class Ui_main_interface(object):
    def setupUi(self, main_interface):
        if not main_interface.objectName():
            main_interface.setObjectName(u"main_interface")
        main_interface.resize(494, 375)
        icon = QIcon()
        icon.addFile(u":/img/icon.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        main_interface.setWindowIcon(icon)
        self.label_2 = QLabel(main_interface)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 20, 151, 91))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QSize(141, 70))
        font = QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"")
        self.label_2.setPixmap(QPixmap(u":/img/logo.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.overview_button = QPushButton(main_interface)
        self.overview_button.setObjectName(u"overview_button")
        self.overview_button.setGeometry(QRect(20, 130, 131, 51))
        font1 = QFont()
        font1.setPointSize(10)
        self.overview_button.setFont(font1)
        self.SATA_Interface_button = QPushButton(main_interface)
        self.SATA_Interface_button.setObjectName(u"SATA_Interface_button")
        self.SATA_Interface_button.setGeometry(QRect(20, 250, 131, 51))
        self.SATA_Interface_button.setFont(font1)
        self.boxmode_button = QPushButton(main_interface)
        self.boxmode_button.setObjectName(u"boxmode_button")
        self.boxmode_button.setGeometry(QRect(20, 190, 131, 51))
        self.boxmode_button.setFont(font1)
        self.boxmode_button.setAutoFillBackground(False)
        self.about_button = QPushButton(main_interface)
        self.about_button.setObjectName(u"about_button")
        self.about_button.setGeometry(QRect(20, 310, 131, 51))
        self.about_button.setFont(font1)
        self.sataconfig = QGroupBox(main_interface)
        self.sataconfig.setObjectName(u"sataconfig")
        self.sataconfig.setEnabled(True)
        self.sataconfig.setGeometry(QRect(170, 10, 311, 351))
        font2 = QFont()
        font2.setItalic(False)
        self.sataconfig.setFont(font2)
        self.sataconfig.setAutoFillBackground(False)
        self.sataconfig.setCheckable(False)
        self.JBOD = QCheckBox(self.sataconfig)
        self.JBOD.setObjectName(u"JBOD")
        self.JBOD.setGeometry(QRect(40, 136, 111, 19))
        self.R1 = QCheckBox(self.sataconfig)
        self.R1.setObjectName(u"R1")
        self.R1.setGeometry(QRect(40, 106, 80, 19))
        self.R0 = QCheckBox(self.sataconfig)
        self.R0.setObjectName(u"R0")
        self.R0.setGeometry(QRect(40, 76, 80, 19))
        self.label = QLabel(self.sataconfig)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 26, 191, 41))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setItalic(False)
        self.label.setFont(font3)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.PM = QCheckBox(self.sataconfig)
        self.PM.setObjectName(u"PM")
        self.PM.setGeometry(QRect(40, 166, 111, 19))
        self.PM.setAcceptDrops(False)
        self.PM.setChecked(True)
        self.sata_execute = QPushButton(self.sataconfig)
        self.sata_execute.setObjectName(u"sata_execute")
        self.sata_execute.setGeometry(QRect(200, 290, 91, 41))
        self.powertime = QSpinBox(self.sataconfig)
        self.powertime.setObjectName(u"powertime")
        self.powertime.setGeometry(QRect(160, 216, 61, 31))
        self.powertime.setMinimum(1)
        self.powertime.setMaximum(10)
        self.label_3 = QLabel(self.sataconfig)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 215, 141, 31))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setItalic(False)
        self.label_3.setFont(font4)
        self.label_4 = QLabel(self.sataconfig)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(230, 220, 53, 21))
        self.boxmode = QGroupBox(main_interface)
        self.boxmode.setObjectName(u"boxmode")
        self.boxmode.setGeometry(QRect(170, 10, 311, 351))
        self.label_5 = QLabel(self.boxmode)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(70, 20, 171, 31))
        self.label_5.setFont(font)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.combinemode = QCheckBox(self.boxmode)
        self.combinemode.setObjectName(u"combinemode")
        self.combinemode.setGeometry(QRect(40, 60, 231, 21))
        self.combinemode.setFont(font1)
        self.nvmeonly = QCheckBox(self.boxmode)
        self.nvmeonly.setObjectName(u"nvmeonly")
        self.nvmeonly.setGeometry(QRect(40, 90, 231, 21))
        self.nvmeonly.setFont(font1)
        self.sataonly = QCheckBox(self.boxmode)
        self.sataonly.setObjectName(u"sataonly")
        self.sataonly.setGeometry(QRect(40, 120, 231, 21))
        self.sataonly.setFont(font1)
        self.label_6 = QLabel(self.boxmode)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(70, 180, 171, 31))
        self.label_6.setFont(font)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.physicalenable = QCheckBox(self.boxmode)
        self.physicalenable.setObjectName(u"physicalenable")
        self.physicalenable.setGeometry(QRect(20, 250, 271, 21))
        self.physicalenable.setFont(font1)
        self.storageconfig = QCheckBox(self.boxmode)
        self.storageconfig.setObjectName(u"storageconfig")
        self.storageconfig.setGeometry(QRect(20, 220, 261, 21))
        self.storageconfig.setFont(font1)
        self.boxmode_execute = QPushButton(self.boxmode)
        self.boxmode_execute.setObjectName(u"boxmode_execute")
        self.boxmode_execute.setGeometry(QRect(200, 290, 91, 41))
        self.hubonly = QCheckBox(self.boxmode)
        self.hubonly.setObjectName(u"hubonly")
        self.hubonly.setGeometry(QRect(40, 150, 231, 21))
        self.hubonly.setFont(font1)
        self.overview = QGroupBox(main_interface)
        self.overview.setObjectName(u"overview")
        self.overview.setGeometry(QRect(170, 10, 311, 351))
        self.about = QGroupBox(main_interface)
        self.about.setObjectName(u"about")
        self.about.setGeometry(QRect(170, 10, 311, 351))
        self.overview.raise_()
        self.about.raise_()
        self.overview_button.raise_()
        self.label_2.raise_()
        self.SATA_Interface_button.raise_()
        self.boxmode_button.raise_()
        self.about_button.raise_()
        self.boxmode.raise_()
        self.sataconfig.raise_()

        self.retranslateUi(main_interface)

        QMetaObject.connectSlotsByName(main_interface)
    # setupUi

    def retranslateUi(self, main_interface):
        main_interface.setWindowTitle(QCoreApplication.translate("main_interface", u"R-SODIUM Ultra SSD Enclosure Manager", None))
        self.label_2.setText("")
        self.overview_button.setText(QCoreApplication.translate("main_interface", u"Overview", None))
        self.SATA_Interface_button.setText(QCoreApplication.translate("main_interface", u"SATA Config", None))
        self.boxmode_button.setText(QCoreApplication.translate("main_interface", u"Box Mode", None))
        self.about_button.setText(QCoreApplication.translate("main_interface", u"About", None))
        self.sataconfig.setTitle("")
        self.JBOD.setText(QCoreApplication.translate("main_interface", u"SPAN / JBOD", None))
        self.R1.setText(QCoreApplication.translate("main_interface", u"RAID 1", None))
        self.R0.setText(QCoreApplication.translate("main_interface", u"RAID 0", None))
        self.label.setText(QCoreApplication.translate("main_interface", u"ASM1352R RAID Config", None))
        self.PM.setText(QCoreApplication.translate("main_interface", u"Normal", None))
        self.sata_execute.setText(QCoreApplication.translate("main_interface", u"Execute", None))
        self.label_3.setText(QCoreApplication.translate("main_interface", u"SATA power-up after", None))
        self.label_4.setText(QCoreApplication.translate("main_interface", u"second/s.", None))
        self.boxmode.setTitle("")
        self.label_5.setText(QCoreApplication.translate("main_interface", u"Enclosure Mode", None))
        self.combinemode.setText(QCoreApplication.translate("main_interface", u"Combine Mode (NVMe + SATA)", None))
        self.nvmeonly.setText(QCoreApplication.translate("main_interface", u"NVMe Only", None))
        self.sataonly.setText(QCoreApplication.translate("main_interface", u"SATA Only", None))
        self.label_6.setText(QCoreApplication.translate("main_interface", u"Other Configuration", None))
        self.physicalenable.setText(QCoreApplication.translate("main_interface", u"Physical switch can still change modes.", None))
        self.storageconfig.setText(QCoreApplication.translate("main_interface", u"Keep mode config for next power up.", None))
        self.boxmode_execute.setText(QCoreApplication.translate("main_interface", u"Execute", None))
        self.hubonly.setText(QCoreApplication.translate("main_interface", u"Hub Only (No disk connected)", None))
        self.overview.setTitle("")
        self.about.setTitle("")
    # retranslateUi

